spring.application.name=corebank

spring.datasource.primary.url=jdbc:postgresql://localhost:5432/corebank
spring.datasource.primary.username=postgres
spring.datasource.primary.password=postgres
spring.datasource.primary.hikari.pool-name=corebank-primary
spring.datasource.primary.hikari.maximum-pool-size=20
spring.datasource.primary.hikari.minimum-idle=5
spring.datasource.primary.hikari.connection-timeout=3000

spring.datasource.replica.url=jdbc:postgresql://localhost:5433/corebank
spring.datasource.replica.username=postgres
spring.datasource.replica.password=postgres
spring.datasource.replica.hikari.pool-name=corebank-replica
spring.datasource.replica.hikari.maximum-pool-size=40
spring.datasource.replica.hikari.minimum-idle=10
spring.datasource.replica.hikari.connection-timeout=3000
spring.datasource.replica.hikari.read-only=true

spring.sql.init.mode=always
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=200ms

corebank.cache.balance-ttl=5s
corebank.outbox.poll-interval=300
corebank.outbox.batch-size=200
